import { useState } from 'react'
import {
  AlertCircle,
  Users,
  Zap,
  TrendingUp,
  XCircle,
  HelpCircle,
  Layers,
  Rocket,
  Copy,
  Check,
  RotateCcw,
  X,
} from 'lucide-react'
import SectionCard from './SectionCard'

const PRIORITY_STYLES = {
  P0: 'bg-red-500/15 text-red-300 border border-red-500/20',
  P1: 'bg-amber-500/15 text-amber-300 border border-amber-500/20',
  P2: 'bg-zinc-700/60 text-zinc-400 border border-zinc-700',
}

function PriorityBadge({ priority }) {
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded-md text-[11px] font-bold tracking-wide ${PRIORITY_STYLES[priority] || PRIORITY_STYLES.P2}`}>
      {priority}
    </span>
  )
}

function AnimatedSection({ children, delay = 0 }) {
  return (
    <div
      className="animate-fade-in"
      style={{ animationDelay: `${delay}s` }}
    >
      {children}
    </div>
  )
}

function formatPRDAsText(prd) {
  const lines = []

  lines.push('PRODUCT REQUIREMENTS DOCUMENT')
  lines.push('Generated by hrishikeshkumar.me')
  lines.push('================================')
  lines.push('')
  lines.push(`PRODUCT: ${prd.productName}`)
  lines.push(prd.oneLiner)
  lines.push('')
  lines.push('PROBLEM STATEMENT')
  lines.push(prd.problemStatement.headline)
  lines.push(prd.problemStatement.context)
  lines.push('')
  lines.push('TARGET USER')
  lines.push(`Primary: ${prd.targetUser.primary}`)
  lines.push('Pain Points:')
  prd.targetUser.painPoints.forEach((p) => lines.push(`• ${p}`))
  lines.push('')
  lines.push('CORE FEATURES')
  prd.coreFeatures.forEach((f) => {
    lines.push(`${f.priority} ${f.name}`)
    lines.push(f.description)
    lines.push(`Why: ${f.rationale}`)
    lines.push('')
  })
  lines.push('SUCCESS METRICS')
  prd.successMetrics.forEach((m) => {
    lines.push(`• ${m.metric}: ${m.target}`)
    lines.push(`  Why: ${m.why}`)
  })
  lines.push('')
  lines.push('OUT OF SCOPE')
  prd.outOfScope.forEach((item) => lines.push(`• ${item}`))
  lines.push('')
  lines.push('OPEN QUESTIONS')
  prd.openQuestions.forEach((q) => {
    lines.push(`Q: ${q.question}`)
    lines.push(`Why it matters: ${q.why}`)
    lines.push('')
  })
  lines.push('RECOMMENDED STACK')
  lines.push(`Frontend: ${prd.recommendedStack.frontend}`)
  lines.push(`Backend: ${prd.recommendedStack.backend}`)
  lines.push(`Database: ${prd.recommendedStack.database}`)
  lines.push(`Key Integrations: ${prd.recommendedStack.keyIntegrations.join(', ')}`)
  lines.push('')
  lines.push('SPRINT 1 GOAL')
  lines.push(prd.sprintOneGoal)
  lines.push('')
  lines.push('================================')
  lines.push('Generated by Hrishikesh Kumar · hrishikeshkumar.me')

  return lines.join('\n')
}

export default function PRDOutput({ prd, onReset }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatPRDAsText(prd))
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      /* clipboard access denied — fail silently */
    }
  }

  return (
    <div className="space-y-4">

      {/* ── 1. Product name + one-liner ── */}
      <AnimatedSection delay={0}>
        <div className="pb-2">
          <h2 className="text-3xl font-bold text-zinc-50 tracking-tight leading-tight">
            {prd.productName}
          </h2>
          <p className="text-zinc-400 mt-1.5 text-base leading-relaxed">
            {prd.oneLiner}
          </p>
        </div>
      </AnimatedSection>

      {/* ── 2. Problem Statement ── */}
      <AnimatedSection delay={0.06}>
        <SectionCard title="Problem Statement" icon={AlertCircle}>
          <p className="font-semibold text-zinc-100 mb-2">{prd.problemStatement.headline}</p>
          <p className="text-zinc-400">{prd.problemStatement.context}</p>
        </SectionCard>
      </AnimatedSection>

      {/* ── 3. Target User ── */}
      <AnimatedSection delay={0.12}>
        <SectionCard title="Target User" icon={Users}>
          <p className="font-medium text-zinc-200 mb-3">{prd.targetUser.primary}</p>
          <ul className="space-y-2">
            {prd.targetUser.painPoints.map((point, i) => (
              <li key={i} className="flex items-start gap-2.5">
                <span className="mt-1 w-1.5 h-1.5 rounded-full bg-indigo-400 flex-shrink-0" />
                <span className="text-zinc-400">{point}</span>
              </li>
            ))}
          </ul>
        </SectionCard>
      </AnimatedSection>

      {/* ── 4. Core Features ── */}
      <AnimatedSection delay={0.18}>
        <SectionCard title="Core Features" icon={Zap}>
          <div className="space-y-3">
            {prd.coreFeatures.map((feature, i) => (
              <div
                key={i}
                className="rounded-xl bg-zinc-950/60 border border-zinc-800/60 p-4 space-y-1.5"
              >
                <div className="flex items-center gap-2.5 flex-wrap">
                  <PriorityBadge priority={feature.priority} />
                  <span className="font-semibold text-zinc-100 text-sm">{feature.name}</span>
                </div>
                <p className="text-zinc-400 text-[13px] leading-relaxed">{feature.description}</p>
                <p className="text-zinc-600 text-[12px] italic">
                  <span className="text-zinc-500 not-italic font-medium">Why: </span>
                  {feature.rationale}
                </p>
              </div>
            ))}
          </div>
        </SectionCard>
      </AnimatedSection>

      {/* ── 5. Success Metrics ── */}
      <AnimatedSection delay={0.24}>
        <SectionCard title="Success Metrics" icon={TrendingUp}>
          <div className="space-y-4">
            {prd.successMetrics.map((metric, i) => (
              <div key={i} className="space-y-0.5">
                <div className="flex items-baseline gap-2 flex-wrap">
                  <span className="font-semibold text-zinc-200 text-sm">{metric.metric}</span>
                  <span className="text-indigo-400 font-bold text-sm">{metric.target}</span>
                </div>
                <p className="text-zinc-500 text-[12px]">{metric.why}</p>
              </div>
            ))}
          </div>
        </SectionCard>
      </AnimatedSection>

      {/* ── 6. Out of Scope ── */}
      <AnimatedSection delay={0.3}>
        <SectionCard title="Out of Scope" icon={XCircle}>
          <ul className="space-y-2">
            {prd.outOfScope.map((item, i) => (
              <li key={i} className="flex items-start gap-2.5">
                <X size={13} className="text-red-400 mt-0.5 flex-shrink-0" />
                <span className="text-zinc-400">{item}</span>
              </li>
            ))}
          </ul>
        </SectionCard>
      </AnimatedSection>

      {/* ── 7. Open Questions ── */}
      <AnimatedSection delay={0.36}>
        <SectionCard title="Open Questions" icon={HelpCircle}>
          <div className="space-y-4">
            {prd.openQuestions.map((q, i) => (
              <div key={i} className="space-y-0.5">
                <p className="font-semibold text-zinc-100 text-sm">{q.question}</p>
                <p className="text-zinc-500 text-[12px]">{q.why}</p>
              </div>
            ))}
          </div>
        </SectionCard>
      </AnimatedSection>

      {/* ── 8. Recommended Stack ── */}
      <AnimatedSection delay={0.42}>
        <SectionCard title="Recommended Stack" icon={Layers}>
          <div className="space-y-3">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <StackItem label="Frontend" value={prd.recommendedStack.frontend} />
              <StackItem label="Backend" value={prd.recommendedStack.backend} />
              <StackItem label="Database" value={prd.recommendedStack.database} />
            </div>
            {prd.recommendedStack.keyIntegrations?.length > 0 && (
              <div>
                <p className="text-xs text-zinc-600 uppercase tracking-widest mb-2">Key Integrations</p>
                <div className="flex flex-wrap gap-2">
                  {prd.recommendedStack.keyIntegrations.map((integration, i) => (
                    <span
                      key={i}
                      className="px-2.5 py-1 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-medium"
                    >
                      {integration}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        </SectionCard>
      </AnimatedSection>

      {/* ── 9. Sprint 1 Goal ── */}
      <AnimatedSection delay={0.48}>
        <div className="rounded-2xl border border-indigo-500/30 bg-indigo-500/5 p-6 relative overflow-hidden">
          {/* Subtle glow background */}
          <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 via-transparent to-transparent pointer-events-none" />

          <div className="relative">
            <div className="flex items-center gap-2.5 mb-3">
              <div className="w-6 h-6 flex items-center justify-center text-indigo-400">
                <Rocket size={15} />
              </div>
              <h2 className="text-xs font-semibold uppercase tracking-widest text-indigo-400">
                Sprint 1 Goal
              </h2>
            </div>
            <p className="text-zinc-100 font-medium leading-relaxed">
              {prd.sprintOneGoal}
            </p>
            <p className="text-indigo-500/60 text-xs mt-3">
              Ship this in 2 weeks to validate the core assumption.
            </p>
          </div>
        </div>
      </AnimatedSection>

      {/* ── Action Buttons ── */}
      <AnimatedSection delay={0.54}>
        <div className="flex flex-wrap gap-3 pt-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl
              bg-zinc-900 border border-zinc-800 text-zinc-300 text-sm font-medium
              hover:border-zinc-700 hover:text-zinc-100 hover:bg-zinc-800
              transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-zinc-950"
          >
            {copied ? (
              <>
                <Check size={15} className="text-emerald-400" />
                <span className="text-emerald-400">Copied!</span>
              </>
            ) : (
              <>
                <Copy size={15} />
                Copy PRD as Text
              </>
            )}
          </button>

          <button
            onClick={onReset}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl
              bg-zinc-900 border border-zinc-800 text-zinc-500 text-sm font-medium
              hover:border-zinc-700 hover:text-zinc-300
              transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-zinc-600 focus:ring-offset-2 focus:ring-offset-zinc-950"
          >
            <RotateCcw size={15} />
            Start Over
          </button>
        </div>
      </AnimatedSection>

    </div>
  )
}

function StackItem({ label, value }) {
  return (
    <div className="rounded-xl bg-zinc-950/60 border border-zinc-800/60 p-3 space-y-0.5">
      <p className="text-[11px] text-zinc-600 uppercase tracking-widest">{label}</p>
      <p className="text-zinc-200 text-sm font-medium">{value}</p>
    </div>
  )
}
